name: Default

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      # You can install dependencies with go get
      - name: Install dependencies
        run: |
          cd ./src
          go get .
      - name: Build
        run: |
          go build -v ./... -ldflags="-X 'main.version=1.1.0'"
      - name: Test with the Go CLI
        run: |
          go test